parameters:
  - name: dependsOn
    type: object
    default: []
  - name: acrName
    type: string
  - name: acrLogin
    type: string
  - name: imageId
    type: string

stages:
- stage: ManageArtifacts
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{ stage }}
  variables: 
    IMAGE_ID: ${{ parameters.imageId }}
  jobs:
  - job: LoginToAzure
    steps:
    - script: az login --identity
      displayName: 'Authenticate to Azure using managed identity'
    - script: podman login ${ACR_NAME}.azurecr.io -u ${ACR_LOGIN} -p $(az acr login -n ${ACR_NAME} --expose-token -o tsv --query accessToken)
      env:
        ACR_NAME: ${{ parameters.acrName }}
        ACR_LOGIN: ${{ parameters.acrLogin }}
      displayName: 'Authenticate to ACR'
  - job: PushImageToArtifactRegistry
    dependsOn: LoginToAzure
    steps:
    - script: |
        #!/bin/bash
        set -xeu -o pipefail
        export NEW_IMAGE_TAG=$(podman image inspect --format '{{index .RepoTags 0}}' $IMAGE_ID |\
        sed "s/^localhost/${ACR_NAME}.azurecr.io/")
        podman tag $IMAGE_ID $NEW_IMAGE_TAG
        podman push $NEW_IMAGE_TAG
      env:
        ACR_NAME: ${{ parameters.acrName }}
      displayName: 'Tag image and push'
