stages:
- stage: PostActions
  condition: always()
  jobs:
  - job: CleanWorkspace
    workspace:
      clean: all
    steps:
    - checkout: none
      displayName: "Skip checkout"
    - script: echo "Cleaning workspace..."
      displayName: "Clean workspace"
