stages:
- stage: Preparation
  jobs:
  - job: DockerPreparation
    steps:
    - script: docker --version
      displayName: 'Check docker/podman version'
    - script: docker run hello-world
      displayName: 'Run hello-world image'
  - job: MavenPreparation
    steps:
    - script: ./mvnw --version
      displayName: 'Check maven version'
