# This manifest is only required for classical passwordless
# approach with manual database changes
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <your_mi_client_id>
  labels:
    app: spring-api-azure-passwordlessdbapp
    app.kubernetes.io/name: spring-api-azure-passwordlessdbapp
    version: v1
    app.kubernetes.io/version: v1
  name: pul-passwordlessdbapp-umi01
  namespace: default
