apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwordlessdbapp
  name: passwordlessdbapp
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: passwordlessdbapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: passwordlessdbapp
        # Important label to mutate pod
        azure.workload.identity/use: "true"
    spec:
      containers:
      - env:
        # DB username is the same as service account name for classical approach with manual DB update
        # - name: DB_USERNAME
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: spec.serviceAccountName
        # For Azure Service Connector, username is included in variable SPRING_DATASOURCE_USERNAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: <your_secret_name>
              key: SPRING_DATASOURCE_USERNAME
        - name: DB_JDBC_STRING
          valueFrom:
            secretKeyRef:
              name: <your_secret_name>
              key: SPRING_DATASOURCE_URL
        image: <your_image_path>
        imagePullPolicy: IfNotPresent
        name: demo
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 2000m
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        startupProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: <your_serviceaccount_name>
