# This manifest is only required for classical passwordless
# approach with manual database changes
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: <your_mi_client_id>
  labels:
    app: passwordlessdbapp
  name: pul-passwordlessdbapp-umi01
  namespace: demo
