apiVersion: v1
kind: Service
metadata:
  labels:
    app: passwordlessdbapp
  name: passwordlessdbapp-svc
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: passwordlessdbapp
  type: ClusterIP
status:
  loadBalancer: {}
