# Redefine Build.BuildNumber
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_build_$(Build.BuildId).$(Rev:rrr)

parameters:
- name: imageToRelease
  displayName: Full path to image to be released (with sha or tag)
  type: string
  default: PUT_FULL_IMAGE_ADDRESS_HERE

trigger: none

# It's required to set variable group before pipeline
variables: 
- group: 'acr_registry'

pool: my-pool

stages:
- template: templates/stage-preparation.yml

- template: templates/stage-manageartifacts.yml
  parameters:
    dependsOn:
    - Preparation
    acrName: $(acr_name)
    acrLogin: $(acr_login)
    imageFullPathWithShaOrTag: ${{ parameters.imageToRelease }}
    release: true

- template: templates/stage-cleanworkspace.yml
