# Redefine Build.BuildNumber
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_build_$(Build.BuildId).$(Rev:rrr)

trigger:
  branches:
    include:
    - 'master'

# It's required to set variable group before pipeline
variables: 
- group: 'acr_registry'

pool: my-pool

stages:
- template: templates/stage-preparation.yml

- template: templates/stage-tests.yml
  parameters:
    # Workaround for potentially missing feature:
    # https://developercommunity.visualstudio.com/t/dependson-should-be-allowed-for-templates/1069661#T-N1393865
    dependsOn:
    - Preparation
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/target/site/jacoco/jacoco.xml'
    pathToSources: '**/src/main/java'
    reportDirectory: '**/target/site/jacoco/'
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- template: templates/stage-createartifacts.yml
  parameters:
    dependsOn:
    - Tests

- template: templates/stage-manageartifacts.yml
  parameters:
    dependsOn:
    - CreateArtifacts
    acrName: $(acr_name)
    acrLogin: $(acr_login)
    imageId: $[ stageDependencies.CreateArtifacts.CreateContainerImage.outputs['getdockerimageid.IMAGE_ID'] ]
